Remove SSL certificates and Nginx configuration files; update React app to handle empty data responses and improve WebSocket connection handling; add entrypoint and initialization scripts for Django deployment; implement supervisor configuration for Gunicorn and Celery; add custom CSS and JS for managing password fields in Django admin.

diff --git a/backend_app/Dockerfile.aws.backend.prod b/backend_app/Dockerfile.aws.backend.prod
--- a/backend_app/Dockerfile.aws.backend.prod
+++ b/backend_app/Dockerfile.aws.backend.prod
@@ -5,33 +5,31 @@ ENV PYTHONPATH=/app
 
 ENV TZ=America/New_York
 
-RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
+RUN ln -fs "/usr/share/zoneinfo/$TZ" /etc/localtime && \
     dpkg-reconfigure -f noninteractive tzdata
 
 WORKDIR /app
 
+# --- Python deps ---
 COPY requirements.txt /app/
 
-RUN pip install --upgrade pip
-RUN pip install gunicorn
-RUN pip install uvicorn
-RUN pip install -r requirements.txt
-
-RUN apt-get update && apt-get install -y wget gnupg2 lsb-release
-
-RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
-RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
-
-RUN apt-get update && apt-get install -y postgresql-client-16
-
+RUN mkdir -p /var/log/supervisor \
+ && mkdir -p /app/backup \
+ && pip install --upgrade pip \
+ && pip install gunicorn \
+ && pip install -r requirements.txt \
+ && apt-get update \
+ && apt-get install -y --no-install-recommends ca-certificates gnupg postgresql-client supervisor wget \
+ && rm -rf /var/lib/apt/lists/*
+ 
 COPY . /app/
+
+COPY _deploy/supervisord.conf /etc/supervisor/supervisord.conf
+COPY _deploy/entrypoint.sh /entrypoint.sh
+RUN chmod +x /entrypoint.sh
 
 EXPOSE 8000
 
-CMD ["sh", "-c", "python manage.py makemigrations && \
-                  python manage.py migrate && \
-                  python manage.py collectstatic --no-input && \
-                  python init_scripts.py && \
-                  celery -A api_project_zoho_senitron worker --loglevel=info -E & \
-                  celery -A api_project_zoho_senitron beat --loglevel=info & \
-                  gunicorn api_project_zoho_senitron.asgi:application -w 3 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"]
+# HEALTHCHECK --interval=30s --timeout=5s --retries=5 CMD wget -qO- http://127.0.0.1:8000/api_qbwc_zoho/health_check/ || exit 1
+
+CMD ["/entrypoint.sh"]
